[build]
  publish   = "frontend/dist"
  command   = "bash ./netlify_build.sh"
  functions = "backend/netlify_functions"

[[redirects]]
  from   = "/api/v0/*"
  to     = "/.netlify/functions/:splat"
  status = 200
